quarkus.http.port=8090
quarkus.http.auth.permission.public.paths=/*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.basic=false
quarkus.http.auth.proactive=false
quarkus.web-bundler.bundle.components=true
quarkus.web-bundler.bundle.components.qute-tags=true
quarkus.web-bundler.bundling.source-map=none
